use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::PathBuf;

#[path = "build/mod.rs"]
mod build;

fn main() {
    gen_keyword_file("ansi", build::ansi::keywords());
    gen_keyword_file("postgres", build::postgres::keywords());
    gen_operator_file("ansi", build::ansi::operators());
    gen_operator_file("postgres", build::postgres::operators());
}

fn gen_operator_file(
    name: &str,
    operators: Vec<(&'static str, u8, &'static str, &'static str, &'static str)>,
) {
    let content = [
        "// This file is auto-generated by build.rs. Do not edit manually.".to_string(),
        "\nuse crate::token::{Assoc, Fixity, OpTag, Operator};".to_string(),
        format!(
            "\npub(crate) static OP_TABLE: phf::Map<&'static str, Operator> = {};",
            build::generate_operator_map(operators)
        ),
    ];
    write_file(format!("src/dialect/{}/operator.rs", name), &content)
}

fn gen_keyword_file(name: &str, keywords: Vec<String>) {
    let content = [
        "// This file is auto-generated by build.rs. Do not edit manually.".to_string(),
        "\nuse crate::token::Keyword;".to_string(),
        format!(
            "\npub(crate) static KEYWORDS: phf::Map<&'static str, Keyword> = {};",
            build::generate_keyword_map(keywords)
        ),
    ];
    write_file(format!("src/dialect/{}/keyword.rs", name), &content)
}

fn write_file(pth: impl Into<PathBuf>, contents: &[String]) {
    let path = pth.into();
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    let mut file = BufWriter::new(File::create(&path).unwrap());
    for line in contents {
        writeln!(&mut file, "{}", line).unwrap();
    }
    drop(file);
}
