use std::fs::File;
use std::fs::{self};
use std::io::BufWriter;
use std::io::Write;
use std::path::PathBuf;

use querent_core::schema;
use ts_rs::TS;

// Define Queries here so we can use TS::decl() on it
#[derive(ts_rs::TS)]
#[ts(optional_fields)]
#[allow(dead_code)]
struct Queries {
    pub functions: Option<String>,
    pub tables: Option<String>,
    pub columns: Option<String>,
}

fn main() {
    let to_export = [
        schema::Cache::decl(),
        schema::DataType::decl(),
        schema::Table::decl(),
        schema::Column::decl(),
        schema::Function::decl(),
        schema::FunctionType::decl(),
        Queries::decl(),
    ];

    let all = to_export
        .into_iter()
        .map(|x| format!("export {}", x))
        .collect::<Vec<String>>()
        .join("\n");

    write_file(
        format!("src/types.rs"),
        &[generate_ts_export_section("CATALOG_TYPES", all)],
    );
}

fn generate_ts_export_section(name: &str, inner: String) -> String {
    let mut content = String::new();
    content.push_str("// This file is auto-generated by build.rs. Do not edit manually.");
    content.push_str("\n\nuse wasm_bindgen::prelude::*;");
    content.push_str("\n\n#[wasm_bindgen(typescript_custom_section)]");
    content.push_str(&format!("\npub const {}: &str = r#\"", name));
    content.push_str("\n");
    content.push_str(&inner);
    content.push_str("\n");
    content.push_str("\"#;");
    content
}

fn write_file(pth: impl Into<PathBuf>, contents: &[String]) {
    let path = pth.into();
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    let mut file = BufWriter::new(File::create(&path).unwrap());
    for line in contents {
        writeln!(&mut file, "{}", line).unwrap();
    }
    drop(file);
}
