// This file is auto-generated by build.rs. Do not edit manually.

use crate::lex::{Assoc, Fixity, OpTag, Operator};

pub(crate) static OPERATORS: phf::Map<&'static str, Operator> = ::phf::Map {
    key: 4203492208743950414,
    disps: &[
        (2, 0),
        (3, 12),
        (13, 0),
        (2, 17),
        (0, 6),
    ],
    entries: &[
        ("<", Operator::new(4, OpTag::Lt, Assoc::None, Fixity::Infix)),
        ("LIKE", Operator::new(4, OpTag::Like, Assoc::None, Fixity::Infix)),
        ("<>", Operator::new(4, OpTag::Neq, Assoc::None, Fixity::Infix)),
        ("AND", Operator::new(2, OpTag::And, Assoc::Left, Fixity::Infix)),
        ("!=", Operator::new(4, OpTag::Neq, Assoc::None, Fixity::Infix)),
        ("-", Operator::new(6, OpTag::Sub, Assoc::Left, Fixity::Infix)),
        ("EXISTS", Operator::new(3, OpTag::Exists, Assoc::Right, Fixity::Prefix)),
        (">=", Operator::new(4, OpTag::Gte, Assoc::None, Fixity::Infix)),
        ("<=", Operator::new(4, OpTag::Lte, Assoc::None, Fixity::Infix)),
        ("IS", Operator::new(4, OpTag::Is, Assoc::None, Fixity::Infix)),
        ("SIMILAR", Operator::new(4, OpTag::Similar, Assoc::None, Fixity::Infix)),
        ("OR", Operator::new(1, OpTag::Or, Assoc::Left, Fixity::Infix)),
        ("+u", Operator::new(8, OpTag::UnaryPlus, Assoc::Right, Fixity::Prefix)),
        (">", Operator::new(4, OpTag::Gt, Assoc::None, Fixity::Infix)),
        ("-u", Operator::new(8, OpTag::UnaryMinus, Assoc::Right, Fixity::Prefix)),
        ("OVERLAPS", Operator::new(4, OpTag::Overlaps, Assoc::None, Fixity::Infix)),
        ("BETWEEN", Operator::new(4, OpTag::Between, Assoc::None, Fixity::Infix)),
        ("=", Operator::new(4, OpTag::Eq, Assoc::None, Fixity::Infix)),
        ("||", Operator::new(5, OpTag::Concat, Assoc::Left, Fixity::Infix)),
        ("NOT", Operator::new(3, OpTag::Not, Assoc::Right, Fixity::Prefix)),
        ("/", Operator::new(7, OpTag::Div, Assoc::Left, Fixity::Infix)),
        ("+", Operator::new(6, OpTag::Add, Assoc::Left, Fixity::Infix)),
        ("IN", Operator::new(4, OpTag::In, Assoc::None, Fixity::Infix)),
        ("*", Operator::new(7, OpTag::Mul, Assoc::Left, Fixity::Infix)),
    ],
};
